name: criptohub
description: "CryptoHub is a robust and intuitive cryptocurrency wallet app, developed with Flutter, that lets users manage their digital assets efficiently."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^0.0.11
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  get_it: ^8.0.3
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6

flutter:
  uses-material-design: true
