name: criptohub
description: "CryptoHub is a robust and intuitive cryptocurrency wallet app, developed with Flutter, that lets users manage their digital assets efficiently."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
